version: '2'
services:
  tour-wp:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - db
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: StrongRootPassword456
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 8088:80
    volumes:
      - ./wordpress:/var/www/html

    networks:
      - tourNetwork
  db:
    image: mysql
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: StrongRootPassword456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: StrongRootPassword456
    networks:
      - tourNetwork
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8089:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: StrongRootPassword456
    networks:
      - tourNetwork
networks:
  tourNetwork:
volumes:
  database:

